
// This file has been generated by the GUI designer. Do not modify.
namespace FrapeSchedSim
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action SaveInitialProcessStateToJPGAction;
		private global::Gtk.Action QuitAction;
		private global::Gtk.Action HowToUseTheSimulatorAction;
		private global::Gtk.Action FileAction1;
		private global::Gtk.Action SaveInitialProcessStateToPNGAction;
		private global::Gtk.Action SaveSchedulingPlanToPNGAction;
		private global::Gtk.Action QuitAction1;
		private global::Gtk.Action HelpAction1;
		private global::Gtk.Action HowToUseTheSimulatorAction1;
		private global::Gtk.Action HowToAddANewAlgorithmAction;
		private global::Gtk.Action AboutThisProgramAction;
		private global::Gtk.Action ProcessesAction;
		private global::Gtk.Action NodesAction;
		private global::Gtk.Action LoadFromXmlAction;
		private global::Gtk.Action SaveToXmlAction;
		private global::Gtk.Action LoadFromXmlAction1;
		private global::Gtk.Action SaveToXmlAction1;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hboxTop;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vboxAlgorithm;
		private global::Gtk.Label labelAlgorithm;
		private global::Gtk.ComboBox comboboxAlgorithm;
		private global::Gtk.Label labelInformation;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewInformation;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.VBox vboxTimeUnits;
		private global::Gtk.Label labelTimeUnits;
		private global::Gtk.SpinButton spinbuttonTimeUnits;
		private global::Gtk.Button buttonRun;
		private global::Gtk.Button buttonRunStepByStep;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Button buttonReset;
		private global::Gtk.Button buttonQuit;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.VBox vboxProcessPool;
		private global::Gtk.Label labelProcessPool;
		private global::Gtk.HBox hboxProcessPoolButtons;
		private global::Gtk.Button buttonAddProcess;
		private global::Gtk.Button buttonRemoveProcess;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.VBox vboxNodePool;
		private global::Gtk.Label labelNodePool;
		private global::Gtk.HBox hboxNodePoolButtons;
		private global::Gtk.Button buttonAddNode;
		private global::Gtk.Button buttonRemoveNode;
		private global::Gtk.VSeparator vseparator5;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hboxMiddle;
		private global::Gtk.VSeparator vseparator6;
		private global::Gtk.VBox vboxInitialProcessState;
		private global::Gtk.Label labelInitialProcess;
		private global::Gtk.ScrolledWindow swInitialProcessState;
		private global::Gtk.VSeparator vseparator7;
		private global::Gtk.VBox vboxRunningProcess;
		private global::Gtk.Label labelRunningProcess;
		private global::Gtk.ScrolledWindow swProcessQueue;
		private global::Gtk.VSeparator vseparator8;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.VBox vboxBottom;
		private global::Gtk.Label labelSchedulingPlan;
		private global::Gtk.ScrolledWindow scrolledwindowSchedPlan;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FrapeSchedSim.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.SaveInitialProcessStateToJPGAction = new global::Gtk.Action ("SaveInitialProcessStateToJPGAction", global::Mono.Unix.Catalog.GetString ("Save Initial Process State to JPG"), null, null);
			this.SaveInitialProcessStateToJPGAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Initial Process State to JPG");
			w1.Add (this.SaveInitialProcessStateToJPGAction, null);
			this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.QuitAction, null);
			this.HowToUseTheSimulatorAction = new global::Gtk.Action ("HowToUseTheSimulatorAction", global::Mono.Unix.Catalog.GetString ("How to use the simulator"), null, null);
			this.HowToUseTheSimulatorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("How to use the simulator");
			w1.Add (this.HowToUseTheSimulatorAction, null);
			this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction1, null);
			this.SaveInitialProcessStateToPNGAction = new global::Gtk.Action ("SaveInitialProcessStateToPNGAction", global::Mono.Unix.Catalog.GetString ("Save Initial Process State to PNG"), null, "gtk-save");
			this.SaveInitialProcessStateToPNGAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Initial Process State to JPG");
			w1.Add (this.SaveInitialProcessStateToPNGAction, null);
			this.SaveSchedulingPlanToPNGAction = new global::Gtk.Action ("SaveSchedulingPlanToPNGAction", global::Mono.Unix.Catalog.GetString ("Save Scheduling Plan to PNG"), null, "gtk-save");
			this.SaveSchedulingPlanToPNGAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Scheduling Plan to JPG");
			w1.Add (this.SaveSchedulingPlanToPNGAction, "<Control>t");
			this.QuitAction1 = new global::Gtk.Action ("QuitAction1", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.QuitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.QuitAction1, null);
			this.HelpAction1 = new global::Gtk.Action ("HelpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction1, null);
			this.HowToUseTheSimulatorAction1 = new global::Gtk.Action ("HowToUseTheSimulatorAction1", global::Mono.Unix.Catalog.GetString ("How to use the simulator"), null, "gtk-help");
			this.HowToUseTheSimulatorAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("How to use the simulator");
			w1.Add (this.HowToUseTheSimulatorAction1, null);
			this.HowToAddANewAlgorithmAction = new global::Gtk.Action ("HowToAddANewAlgorithmAction", global::Mono.Unix.Catalog.GetString ("How to add a new algorithm"), null, "gtk-help");
			this.HowToAddANewAlgorithmAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("How to add a new algorithm");
			w1.Add (this.HowToAddANewAlgorithmAction, null);
			this.AboutThisProgramAction = new global::Gtk.Action ("AboutThisProgramAction", global::Mono.Unix.Catalog.GetString ("About this program"), null, "gtk-dialog-info");
			this.AboutThisProgramAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About this program");
			w1.Add (this.AboutThisProgramAction, null);
			this.ProcessesAction = new global::Gtk.Action ("ProcessesAction", global::Mono.Unix.Catalog.GetString ("Processes"), null, "gtk-copy");
			this.ProcessesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Processes");
			w1.Add (this.ProcessesAction, "<Control>p");
			this.NodesAction = new global::Gtk.Action ("NodesAction", global::Mono.Unix.Catalog.GetString ("Nodes"), null, "gtk-network");
			this.NodesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nodes");
			w1.Add (this.NodesAction, "<Control>n");
			this.LoadFromXmlAction = new global::Gtk.Action ("LoadFromXmlAction", global::Mono.Unix.Catalog.GetString ("Load from Xml"), null, null);
			this.LoadFromXmlAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load from Xml");
			w1.Add (this.LoadFromXmlAction, null);
			this.SaveToXmlAction = new global::Gtk.Action ("SaveToXmlAction", global::Mono.Unix.Catalog.GetString ("Save to Xml"), null, null);
			this.SaveToXmlAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save to Xml");
			w1.Add (this.SaveToXmlAction, null);
			this.LoadFromXmlAction1 = new global::Gtk.Action ("LoadFromXmlAction1", global::Mono.Unix.Catalog.GetString ("Load from Xml"), null, null);
			this.LoadFromXmlAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load from Xml");
			w1.Add (this.LoadFromXmlAction1, null);
			this.SaveToXmlAction1 = new global::Gtk.Action ("SaveToXmlAction1", global::Mono.Unix.Catalog.GetString ("Save to Xml"), null, null);
			this.SaveToXmlAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save to Xml");
			w1.Add (this.SaveToXmlAction1, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "FrapeSchedSim.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("FrapeSchedSim - Scheduling Simulator for Frapes");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("FrapeSchedSim.soft_drink_256.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child FrapeSchedSim.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction1' action='FileAction1'><menu name='ProcessesAction' action='ProcessesAction'><menuitem name='LoadFromXmlAction' action='LoadFromXmlAction'/><menuitem name='SaveToXmlAction' action='SaveToXmlAction'/></menu><menu name='NodesAction' action='NodesAction'><menuitem name='LoadFromXmlAction1' action='LoadFromXmlAction1'/><menuitem name='SaveToXmlAction1' action='SaveToXmlAction1'/></menu><separator/><menuitem name='QuitAction1' action='QuitAction1'/></menu><menu name='HelpAction1' action='HelpAction1'><menuitem name='AboutThisProgramAction' action='AboutThisProgramAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vboxMain.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vboxMain.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hseparator1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxTop = new global::Gtk.HBox ();
			this.hboxTop.Name = "hboxTop";
			this.hboxTop.Spacing = 6;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hboxTop.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vseparator1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vboxAlgorithm = new global::Gtk.VBox ();
			this.vboxAlgorithm.Name = "vboxAlgorithm";
			this.vboxAlgorithm.Spacing = 6;
			// Container child vboxAlgorithm.Gtk.Box+BoxChild
			this.labelAlgorithm = new global::Gtk.Label ();
			this.labelAlgorithm.Name = "labelAlgorithm";
			this.labelAlgorithm.LabelProp = global::Mono.Unix.Catalog.GetString ("Algorithm:");
			this.vboxAlgorithm.Add (this.labelAlgorithm);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxAlgorithm [this.labelAlgorithm]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxAlgorithm.Gtk.Box+BoxChild
			this.comboboxAlgorithm = global::Gtk.ComboBox.NewText ();
			this.comboboxAlgorithm.WidthRequest = 220;
			this.comboboxAlgorithm.CanFocus = true;
			this.comboboxAlgorithm.Name = "comboboxAlgorithm";
			this.vboxAlgorithm.Add (this.comboboxAlgorithm);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxAlgorithm [this.comboboxAlgorithm]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxAlgorithm.Gtk.Box+BoxChild
			this.labelInformation = new global::Gtk.Label ();
			this.labelInformation.Name = "labelInformation";
			this.labelInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("Information:");
			this.vboxAlgorithm.Add (this.labelInformation);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxAlgorithm [this.labelInformation]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxAlgorithm.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewInformation = new global::Gtk.TextView ();
			this.textviewInformation.HeightRequest = 120;
			this.textviewInformation.CanFocus = true;
			this.textviewInformation.Name = "textviewInformation";
			this.textviewInformation.Editable = false;
			this.textviewInformation.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.textviewInformation);
			this.vboxAlgorithm.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxAlgorithm [this.GtkScrolledWindow]));
			w9.Position = 3;
			this.hboxTop.Add (this.vboxAlgorithm);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vboxAlgorithm]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hboxTop.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vseparator2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vboxTimeUnits = new global::Gtk.VBox ();
			this.vboxTimeUnits.Name = "vboxTimeUnits";
			this.vboxTimeUnits.Spacing = 6;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.labelTimeUnits = new global::Gtk.Label ();
			this.labelTimeUnits.Name = "labelTimeUnits";
			this.labelTimeUnits.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulation Time Units:");
			this.vboxTimeUnits.Add (this.labelTimeUnits);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.labelTimeUnits]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.spinbuttonTimeUnits = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbuttonTimeUnits.CanFocus = true;
			this.spinbuttonTimeUnits.Name = "spinbuttonTimeUnits";
			this.spinbuttonTimeUnits.Adjustment.PageIncrement = 10;
			this.spinbuttonTimeUnits.ClimbRate = 1;
			this.spinbuttonTimeUnits.Numeric = true;
			this.spinbuttonTimeUnits.Value = 20;
			this.vboxTimeUnits.Add (this.spinbuttonTimeUnits);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.spinbuttonTimeUnits]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.buttonRun = new global::Gtk.Button ();
			this.buttonRun.CanFocus = true;
			this.buttonRun.Name = "buttonRun";
			this.buttonRun.UseUnderline = true;
			// Container child buttonRun.Gtk.Container+ContainerChild
			global::Gtk.Alignment w14 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w15 = new global::Gtk.HBox ();
			w15.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w15.Add (w16);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w18 = new global::Gtk.Label ();
			w18.LabelProp = global::Mono.Unix.Catalog.GetString ("Run Simulation");
			w18.UseUnderline = true;
			w15.Add (w18);
			w14.Add (w15);
			this.buttonRun.Add (w14);
			this.vboxTimeUnits.Add (this.buttonRun);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.buttonRun]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.buttonRunStepByStep = new global::Gtk.Button ();
			this.buttonRunStepByStep.CanFocus = true;
			this.buttonRunStepByStep.Name = "buttonRunStepByStep";
			this.buttonRunStepByStep.UseUnderline = true;
			// Container child buttonRunStepByStep.Gtk.Container+ContainerChild
			global::Gtk.Alignment w23 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w24 = new global::Gtk.HBox ();
			w24.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-next", global::Gtk.IconSize.Menu);
			w24.Add (w25);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w27 = new global::Gtk.Label ();
			w27.LabelProp = global::Mono.Unix.Catalog.GetString ("Run Step By Step");
			w27.UseUnderline = true;
			w24.Add (w27);
			w23.Add (w24);
			this.buttonRunStepByStep.Add (w23);
			this.vboxTimeUnits.Add (this.buttonRunStepByStep);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.buttonRunStepByStep]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vboxTimeUnits.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.hseparator3]));
			w32.Position = 4;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.buttonReset = new global::Gtk.Button ();
			this.buttonReset.CanFocus = true;
			this.buttonReset.Name = "buttonReset";
			this.buttonReset.UseUnderline = true;
			// Container child buttonReset.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-stop", global::Gtk.IconSize.Menu);
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w37.LabelProp = global::Mono.Unix.Catalog.GetString ("Reset Simulation");
			w37.UseUnderline = true;
			w34.Add (w37);
			w33.Add (w34);
			this.buttonReset.Add (w33);
			this.vboxTimeUnits.Add (this.buttonReset);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.buttonReset]));
			w41.Position = 5;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vboxTimeUnits.Gtk.Box+BoxChild
			this.buttonQuit = new global::Gtk.Button ();
			this.buttonQuit.CanFocus = true;
			this.buttonQuit.Name = "buttonQuit";
			this.buttonQuit.UseUnderline = true;
			// Container child buttonQuit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Quit Program");
			w46.UseUnderline = true;
			w43.Add (w46);
			w42.Add (w43);
			this.buttonQuit.Add (w42);
			this.vboxTimeUnits.Add (this.buttonQuit);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxTimeUnits [this.buttonQuit]));
			w50.Position = 6;
			w50.Expand = false;
			w50.Fill = false;
			this.hboxTop.Add (this.vboxTimeUnits);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vboxTimeUnits]));
			w51.Position = 3;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hboxTop.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vseparator3]));
			w52.Position = 4;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vboxProcessPool = new global::Gtk.VBox ();
			this.vboxProcessPool.Name = "vboxProcessPool";
			this.vboxProcessPool.Spacing = 6;
			// Container child vboxProcessPool.Gtk.Box+BoxChild
			this.labelProcessPool = new global::Gtk.Label ();
			this.labelProcessPool.Name = "labelProcessPool";
			this.labelProcessPool.LabelProp = global::Mono.Unix.Catalog.GetString ("Process Pool");
			this.vboxProcessPool.Add (this.labelProcessPool);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxProcessPool [this.labelProcessPool]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vboxProcessPool.Gtk.Box+BoxChild
			this.hboxProcessPoolButtons = new global::Gtk.HBox ();
			this.hboxProcessPoolButtons.Name = "hboxProcessPoolButtons";
			this.hboxProcessPoolButtons.Spacing = 6;
			// Container child hboxProcessPoolButtons.Gtk.Box+BoxChild
			this.buttonAddProcess = new global::Gtk.Button ();
			this.buttonAddProcess.CanFocus = true;
			this.buttonAddProcess.Name = "buttonAddProcess";
			this.buttonAddProcess.UseUnderline = true;
			// Container child buttonAddProcess.Gtk.Container+ContainerChild
			global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w55 = new global::Gtk.HBox ();
			w55.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w55.Add (w56);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w58 = new global::Gtk.Label ();
			w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Add Process");
			w58.UseUnderline = true;
			w55.Add (w58);
			w54.Add (w55);
			this.buttonAddProcess.Add (w54);
			this.hboxProcessPoolButtons.Add (this.buttonAddProcess);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hboxProcessPoolButtons [this.buttonAddProcess]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hboxProcessPoolButtons.Gtk.Box+BoxChild
			this.buttonRemoveProcess = new global::Gtk.Button ();
			this.buttonRemoveProcess.CanFocus = true;
			this.buttonRemoveProcess.Name = "buttonRemoveProcess";
			this.buttonRemoveProcess.UseUnderline = true;
			// Container child buttonRemoveProcess.Gtk.Container+ContainerChild
			global::Gtk.Alignment w63 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w64 = new global::Gtk.HBox ();
			w64.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w65 = new global::Gtk.Image ();
			w65.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w64.Add (w65);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w67 = new global::Gtk.Label ();
			w67.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove Process");
			w67.UseUnderline = true;
			w64.Add (w67);
			w63.Add (w64);
			this.buttonRemoveProcess.Add (w63);
			this.hboxProcessPoolButtons.Add (this.buttonRemoveProcess);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hboxProcessPoolButtons [this.buttonRemoveProcess]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			this.vboxProcessPool.Add (this.hboxProcessPoolButtons);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vboxProcessPool [this.hboxProcessPoolButtons]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			this.hboxTop.Add (this.vboxProcessPool);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vboxProcessPool]));
			w73.Position = 5;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hboxTop.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vseparator4]));
			w74.Position = 6;
			w74.Expand = false;
			w74.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vboxNodePool = new global::Gtk.VBox ();
			this.vboxNodePool.Name = "vboxNodePool";
			this.vboxNodePool.Spacing = 6;
			// Container child vboxNodePool.Gtk.Box+BoxChild
			this.labelNodePool = new global::Gtk.Label ();
			this.labelNodePool.Name = "labelNodePool";
			this.labelNodePool.LabelProp = global::Mono.Unix.Catalog.GetString ("Node Pool");
			this.vboxNodePool.Add (this.labelNodePool);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vboxNodePool [this.labelNodePool]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vboxNodePool.Gtk.Box+BoxChild
			this.hboxNodePoolButtons = new global::Gtk.HBox ();
			this.hboxNodePoolButtons.Name = "hboxNodePoolButtons";
			this.hboxNodePoolButtons.Spacing = 6;
			// Container child hboxNodePoolButtons.Gtk.Box+BoxChild
			this.buttonAddNode = new global::Gtk.Button ();
			this.buttonAddNode.CanFocus = true;
			this.buttonAddNode.Name = "buttonAddNode";
			this.buttonAddNode.UseUnderline = true;
			// Container child buttonAddNode.Gtk.Container+ContainerChild
			global::Gtk.Alignment w76 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w77 = new global::Gtk.HBox ();
			w77.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w78 = new global::Gtk.Image ();
			w78.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w77.Add (w78);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w80 = new global::Gtk.Label ();
			w80.LabelProp = global::Mono.Unix.Catalog.GetString ("Add Node");
			w80.UseUnderline = true;
			w77.Add (w80);
			w76.Add (w77);
			this.buttonAddNode.Add (w76);
			this.hboxNodePoolButtons.Add (this.buttonAddNode);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hboxNodePoolButtons [this.buttonAddNode]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child hboxNodePoolButtons.Gtk.Box+BoxChild
			this.buttonRemoveNode = new global::Gtk.Button ();
			this.buttonRemoveNode.CanFocus = true;
			this.buttonRemoveNode.Name = "buttonRemoveNode";
			this.buttonRemoveNode.UseUnderline = true;
			// Container child buttonRemoveNode.Gtk.Container+ContainerChild
			global::Gtk.Alignment w85 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w86 = new global::Gtk.HBox ();
			w86.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w87 = new global::Gtk.Image ();
			w87.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w86.Add (w87);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w89 = new global::Gtk.Label ();
			w89.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove Node");
			w89.UseUnderline = true;
			w86.Add (w89);
			w85.Add (w86);
			this.buttonRemoveNode.Add (w85);
			this.hboxNodePoolButtons.Add (this.buttonRemoveNode);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hboxNodePoolButtons [this.buttonRemoveNode]));
			w93.Position = 1;
			w93.Expand = false;
			w93.Fill = false;
			this.vboxNodePool.Add (this.hboxNodePoolButtons);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vboxNodePool [this.hboxNodePoolButtons]));
			w94.Position = 2;
			w94.Expand = false;
			w94.Fill = false;
			this.hboxTop.Add (this.vboxNodePool);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vboxNodePool]));
			w95.Position = 7;
			w95.Expand = false;
			w95.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator ();
			this.vseparator5.Name = "vseparator5";
			this.hboxTop.Add (this.vseparator5);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hboxTop [this.vseparator5]));
			w96.Position = 8;
			w96.Expand = false;
			w96.Fill = false;
			this.vboxMain.Add (this.hboxTop);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxTop]));
			w97.Position = 2;
			w97.Expand = false;
			w97.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vboxMain.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hseparator2]));
			w98.Position = 3;
			w98.Expand = false;
			w98.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxMiddle = new global::Gtk.HBox ();
			this.hboxMiddle.Name = "hboxMiddle";
			this.hboxMiddle.Spacing = 6;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vseparator6 = new global::Gtk.VSeparator ();
			this.vseparator6.Name = "vseparator6";
			this.hboxMiddle.Add (this.vseparator6);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.vseparator6]));
			w99.Position = 0;
			w99.Expand = false;
			w99.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vboxInitialProcessState = new global::Gtk.VBox ();
			this.vboxInitialProcessState.Name = "vboxInitialProcessState";
			this.vboxInitialProcessState.Spacing = 6;
			// Container child vboxInitialProcessState.Gtk.Box+BoxChild
			this.labelInitialProcess = new global::Gtk.Label ();
			this.labelInitialProcess.Name = "labelInitialProcess";
			this.labelInitialProcess.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Process State");
			this.vboxInitialProcessState.Add (this.labelInitialProcess);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vboxInitialProcessState [this.labelInitialProcess]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child vboxInitialProcessState.Gtk.Box+BoxChild
			this.swInitialProcessState = new global::Gtk.ScrolledWindow ();
			this.swInitialProcessState.WidthRequest = 450;
			this.swInitialProcessState.HeightRequest = 150;
			this.swInitialProcessState.CanFocus = true;
			this.swInitialProcessState.Name = "swInitialProcessState";
			this.swInitialProcessState.ShadowType = ((global::Gtk.ShadowType)(3));
			this.vboxInitialProcessState.Add (this.swInitialProcessState);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vboxInitialProcessState [this.swInitialProcessState]));
			w101.Position = 1;
			w101.Expand = false;
			w101.Fill = false;
			this.hboxMiddle.Add (this.vboxInitialProcessState);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.vboxInitialProcessState]));
			w102.Position = 1;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vseparator7 = new global::Gtk.VSeparator ();
			this.vseparator7.Name = "vseparator7";
			this.hboxMiddle.Add (this.vseparator7);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.vseparator7]));
			w103.Position = 2;
			w103.Expand = false;
			w103.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vboxRunningProcess = new global::Gtk.VBox ();
			this.vboxRunningProcess.Name = "vboxRunningProcess";
			this.vboxRunningProcess.Spacing = 6;
			// Container child vboxRunningProcess.Gtk.Box+BoxChild
			this.labelRunningProcess = new global::Gtk.Label ();
			this.labelRunningProcess.Name = "labelRunningProcess";
			this.labelRunningProcess.LabelProp = global::Mono.Unix.Catalog.GetString ("Running Process Queue");
			this.vboxRunningProcess.Add (this.labelRunningProcess);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vboxRunningProcess [this.labelRunningProcess]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child vboxRunningProcess.Gtk.Box+BoxChild
			this.swProcessQueue = new global::Gtk.ScrolledWindow ();
			this.swProcessQueue.CanFocus = true;
			this.swProcessQueue.Name = "swProcessQueue";
			this.swProcessQueue.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vboxRunningProcess.Add (this.swProcessQueue);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vboxRunningProcess [this.swProcessQueue]));
			w105.Position = 1;
			this.hboxMiddle.Add (this.vboxRunningProcess);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.vboxRunningProcess]));
			w106.Position = 3;
			w106.Expand = false;
			w106.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vseparator8 = new global::Gtk.VSeparator ();
			this.vseparator8.Name = "vseparator8";
			this.hboxMiddle.Add (this.vseparator8);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.vseparator8]));
			w107.Position = 4;
			w107.Expand = false;
			w107.Fill = false;
			this.vboxMain.Add (this.hboxMiddle);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxMiddle]));
			w108.Position = 4;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vboxMain.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hseparator4]));
			w109.Position = 5;
			w109.Expand = false;
			w109.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxBottom = new global::Gtk.VBox ();
			this.vboxBottom.Name = "vboxBottom";
			this.vboxBottom.Spacing = 6;
			// Container child vboxBottom.Gtk.Box+BoxChild
			this.labelSchedulingPlan = new global::Gtk.Label ();
			this.labelSchedulingPlan.Name = "labelSchedulingPlan";
			this.labelSchedulingPlan.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Scheduling Plan</b>");
			this.labelSchedulingPlan.UseMarkup = true;
			this.vboxBottom.Add (this.labelSchedulingPlan);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vboxBottom [this.labelSchedulingPlan]));
			w110.Position = 0;
			w110.Expand = false;
			w110.Fill = false;
			// Container child vboxBottom.Gtk.Box+BoxChild
			this.scrolledwindowSchedPlan = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowSchedPlan.HeightRequest = 230;
			this.scrolledwindowSchedPlan.CanFocus = true;
			this.scrolledwindowSchedPlan.Name = "scrolledwindowSchedPlan";
			this.scrolledwindowSchedPlan.ShadowType = ((global::Gtk.ShadowType)(3));
			this.vboxBottom.Add (this.scrolledwindowSchedPlan);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vboxBottom [this.scrolledwindowSchedPlan]));
			w111.Position = 1;
			w111.Expand = false;
			w111.Fill = false;
			this.vboxMain.Add (this.vboxBottom);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.vboxBottom]));
			w112.Position = 6;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1057;
			this.DefaultHeight = 790;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.FocusActivated += new global::System.EventHandler (this.OnFocusActivated);
			this.SaveInitialProcessStateToPNGAction.Activated += new global::System.EventHandler (this.OnSaveInitialProcessStateToJPGAction1Activated);
			this.SaveSchedulingPlanToPNGAction.Activated += new global::System.EventHandler (this.OnSaveSchedulingPlanToPNGActionActivated);
			this.QuitAction1.Activated += new global::System.EventHandler (this.OnQuitAction1Activated);
			this.AboutThisProgramAction.Activated += new global::System.EventHandler (this.OnAboutThisProgramActionActivated);
			this.LoadFromXmlAction.Activated += new global::System.EventHandler (this.OnLoadFromXmlActionActivated);
			this.SaveToXmlAction.Activated += new global::System.EventHandler (this.OnSaveToXmlActionActivated);
			this.LoadFromXmlAction1.Activated += new global::System.EventHandler (this.OnLoadFromXmlAction1Activated);
			this.SaveToXmlAction1.Activated += new global::System.EventHandler (this.OnSaveToXmlAction1Activated);
			this.comboboxAlgorithm.Changed += new global::System.EventHandler (this.OnComboboxAlgorithmChanged);
			this.buttonRun.Clicked += new global::System.EventHandler (this.OnButtonRunClicked);
			this.buttonRunStepByStep.Clicked += new global::System.EventHandler (this.OnButtonRunStepByStepClicked);
			this.buttonReset.Clicked += new global::System.EventHandler (this.OnButtonResetClicked);
			this.buttonQuit.Clicked += new global::System.EventHandler (this.OnButtonQuitClicked);
			this.buttonAddProcess.Clicked += new global::System.EventHandler (this.OnButtonAddProcessClicked);
			this.buttonRemoveProcess.Clicked += new global::System.EventHandler (this.OnButtonRemoveProcessClicked);
			this.buttonAddNode.Clicked += new global::System.EventHandler (this.OnButtonAddNodeClicked);
			this.buttonRemoveNode.Clicked += new global::System.EventHandler (this.OnButtonRemoveNodeClicked);
		}
	}
}
